datafusion/Cargo.toml, datafusion/src/cube_ext/datetime.rs, datafusion/src/cube_ext/mod.rs, datafusion/src/cube_ext/rolling.rs, datafusion/src/cube_ext/util.rs, datafusion/src/logical_plan/builder.rs, datafusion/src/logical_plan/expr.rs, datafusion/src/logical_plan/window_frames.rs, datafusion/src/optimizer/utils.rs, datafusion/src/physical_plan/hash_aggregate.rs, datafusion/src/physical_plan/merge_sort.rs, datafusion/src/physical_plan/planner.rs, datafusion/src/physical_plan/windows/aggregate.rs, datafusion/src/sql/planner.rs, datafusion/src/sql/utils.rs
CubeStore extension to implement rolling window measures in CubeJS.
Tests are in the CubeStore repository.
The syntax is of the form:
```
SELECT dim, key1, key2, other,
ROLLING(SUM(x) RANGE BETWEEN 7 PRECEDING AND UNBOUNDED FOLLOWING)
ROLLING(AVG(x) RANGE BETWEEN 7 PRECEDING AND UNBOUNDED FOLLOWING)
FROM input
ROLLING_WINDOW
DIMENSION dim
PARTITION BY key1, key2
FROM 0 to 10 EVERY 2
```
Semantics are roughly:
- compute rolling window aggregations over input data,
- window "rolls over" the `DIMENSION` column, only values defined in
the range by `FROM .. TO .. EVERY ..` are reported,
- each "group" defined by columns in `PARTITION BY` is handled
and reported independently,
Current limitations:
- only ranges with up to 10M points are supported to avoid infinite
loops are accidental DOS. This …
=> Rolling window queries

datafusion/src/cube_ext/mod.rs, datafusion/src/cube_ext/ordfloat.rs, datafusion/src/physical_plan/group_scalar.rs, datafusion/src/physical_plan/hash_aggregate.rs, datafusion/src/physical_plan/merge_sort.rs
Current implementation incorrectly equates negative zero and zero.
This can produce invalid results on merge and compactions in CubeStore.
=> Use total order to compare floats in grouping

datafusion/core/src/sql/planner.rs
This PR adds support for ::text type conversion, allowing queries like `SELECT NULL::text`.
=> feat: Support ::text type conversion

ballista/rust/core/Cargo.toml, ballista/rust/executor/Cargo.toml, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/datetime_expressions.rs
This PR adds support for `quarter` field in `date_part` SQL function.
Since this requires a change in arrow, fork's arrow-related crates are used for the time being.
Note: see [this commit to arrow-rs](https://github.com/cube-js/arrow-rs/commit/01aa59d11110fd33b389cab0bf679b99db9e10e2) before approving.
=> feat: Support `quarter` field in `date_part` SQL function

datafusion/core/src/execution/context.rs, datafusion/core/src/physical_plan/subquery.rs
This PR fixes subqueries returning empty result set to coerce to `NULL`.
Also repartitioning is disabled for the time being as it introduces race conditions with subqueries, breaking queries returning non-empty result sets.
=> fix: Coerce empty subquery result to `NULL`

ballista/rust/core/Cargo.toml, ballista/rust/executor/Cargo.toml, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/core/src/optimizer/projection_push_down.rs, datafusion/core/src/physical_plan/functions.rs, datafusion/core/src/physical_plan/join_utils.rs, datafusion/core/src/sql/planner.rs, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml
This PR normalizes column names for joins in ProjectionPushDown, adding support for joins with an aliased FROM subquery and uppercase column names.
It also [bumps `arrow-rs`](https://github.com/cube-js/arrow-rs/commit/52d28cdd32e7b7fb9997a2e6bb187f0a64392573) to fix column search with uppercase aliases by normalizing field names before searching.
Additionally, it fixes UDTF error handling to propagate to protocol errors instead of unsafely unwrapping them.
=> fix: Normalize column names for joins and aliased columns

datafusion/core/src/physical_plan/hash_join.rs, datafusion/core/src/sql/planner.rs, datafusion/core/tests/sql/joins.rs
This PR fixes queries that use `JOIN` with `AND` and `OR` over the same field and lose data, returning 0 rows.
=> fix(cubesql): Fix data loss on `JOIN` with `AND` + `OR`

ballista/rust/core/Cargo.toml, ballista/rust/executor/Cargo.toml, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/core/src/physical_plan/planner.rs, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/coercion_rule/binary_rule.rs
This PR adds support for Utf8 and Boolean equality coercion, allowing queries such as `SELECT FALSE = 'f'`.
=> Support Utf8 and Boolean equality coercion

datafusion/core/src/physical_plan/table_fun.rs
This PR fixes behavior of `TableFunStream` when no batch sections are present. Previously, sections would be passed to `arrow`'s `concat` which intentionally does not handle empty arrays. An introduced fix eliminates the issue by checking if there are any sections first, returning an empty batch for the case.
=> fix: Correct UDTF behavior when no batch sections are present

ballista/rust/client/Cargo.toml, ballista/rust/core/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/expr/Cargo.toml
This PR bumps `sqlparser-rs` to support `LOCALTIME` and `LOCALTIMESTAMP` as parentheses-less functions like `CURRENT_TIMESTAMP`.
=> chore: Bump cube-js/sqlparser-rs@952bb1b

datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/expr/Cargo.toml
This PR bumps `sqlparser-rs` in order to fix `INTERVAL` syntax parsing with non-PostgreSQL dialects.
=> chore: Bump cube-js/sqlparser-rs@13aff89

datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/expr/Cargo.toml
This PR bumps cube-js/sqlparser-rs@ef389d8 to allow `EXTRACT` date/time field to be parsed as a string.
=> chore: Bump cube-js/sqlparser-rs@ef389d8

datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/expr/Cargo.toml
This PR bumps cube-js/sqlparser-rs@2b18e22 allowing AST parsing of `POSITION(substr IN str)` function. No actual DataFusion support is added.
=> chore: Bump cube-js/sqlparser-rs@2b18e22

datafusion/core/src/physical_plan/aggregates.rs, datafusion/expr/src/aggregate_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/coercion_rule/aggregate_rule.rs, datafusion/physical-expr/src/expressions/bool_and_or.rs, datafusion/physical-expr/src/expressions/mod.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/from_proto.rs, datafusion/proto/src/to_proto.rs
This PR adds support for [`bool_and` and `bool_or` aggregate functions](https://www.postgresql.org/docs/current/functions-aggregate.html), plus related tests.
=> feat: Add `bool_and`, `bool_or` aggregate functions

datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml
This PR bumps cube-js/arrow-rs@d0466ec, allowing date to string casts.
=> chore: Bump cube-js/arrow-rs@d0466ec

Cargo.lock, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml
This PR bumps cube-js/arrow-rs@9025ed8, fixing an issue with `[NOT] [I]LIKE` operator not recognizing escape characters, thus being unable to match `_` or `%` symbols explicitly.
=> chore: Bump cube-js/arrow-rs@9025ed8

Cargo.lock, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml
This PR bumps cube-js/sqlparser-rs@883cc6a to allow `APPROXIMATE` keyword in front of aggregate functions (such as `COUNT`), used in Redshift. It also bumps cube-js/arrow-rs@51f62a7.
=> Bump cube-js/sqlparser-rs@883cc6a, cube-js/arrow-rs@51f62a7

.github/workflows/rust.yml, Cargo.lock, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/coercion_rule/binary_rule.rs
This PR bumps cube-js/arrow-rs@096ef28, adding support for casting `Date32` to `Timestamp`.
=> chore: Bump cube-js/arrow-rs@096ef28

datafusion/core/src/physical_plan/functions.rs, datafusion/core/tests/sql/expr.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/regex_expressions.rs
This PR adds support for two-argument `regexp_replace` variant where the replacer is missing and is assumed to be an empty string. Related tests are added.
=> feat: Support `regexp_replace` default empty replacer

datafusion/core/src/physical_plan/functions.rs, datafusion/physical-expr/src/coercion_rule/binary_rule.rs, datafusion/physical-expr/src/datetime_expressions.rs
This PR adds changes that improve Thoughtspot compatibility:
- Allow `Date32` as an argument to `date_trunc` in initial plan
- Allow `Date32 - Date32` expressions in initial plan
=> chore: Improve Thoughtspot Postgres compatibility

datafusion/core/src/physical_plan/planner.rs, datafusion/core/tests/sql/expr.rs, datafusion/physical-expr/src/coercion_rule/binary_rule.rs, datafusion/physical-expr/src/expressions/binary.rs
This PR fixes comparison between `Utf8(NULL)` and number/boolean types. Related tests are included.
=> fix: NULL comparison with numbers and booleans

Cargo.lock, datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/src/optimizer/filter_push_down.rs, datafusion/core/src/optimizer/utils.rs, datafusion/core/src/sql/planner.rs, datafusion/core/tests/sql/aggregates.rs, datafusion/expr/Cargo.toml
This PR improves support of LangChain, fixing introspection issues. The included fixes are:
- Ignore `pg_catalog` schema in compound identifiers (such as `SELECT pg_catalog.pg_class.oid`)
- Fix alias rewriting for IN expressions. Previously an IN expression in WHERE could not refer to columns from realiased tables
- `ARRAY_AGG` function supports extended syntax `ARRAY_AGG( [ DISTINCT ] <expr> [ORDER BY <expr>] [LIMIT <n>] )`. Only `ORDER BY` is supported as a stub; there is no effect providing ORDER BY for now.
Related tests are included.
=> feat: Improve LangChain support

datafusion/core/src/physical_plan/functions.rs, datafusion/core/tests/sql/timestamp.rs, datafusion/expr/src/built_in_function.rs, datafusion/expr/src/expr_fn.rs, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/proto/proto/datafusion.proto, datafusion/proto/src/from_proto.rs, datafusion/proto/src/to_proto.rs
This PR cherry-picks upstream `current_date` support. Test is included.
=> feat: Support `current_date` scalar function

.github/workflows/rust.yml, Cargo.lock, datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/expr/Cargo.toml
This PR bumps cube-js/sqlparser-rs@ac5fc7c, allowing setting multiple values with `SET` with PostgreSQL or Redshift syntax, e.g. `SET a = b, c`.
One case where this is problematic is `SET search_path = public, other_schema` with PostgreSQL. Such a query is issued, for instance, by DBeaver.
=> feat: Support multiple values in `SET`

datafusion/core/src/physical_plan/functions.rs, datafusion/core/src/physical_plan/type_coercion.rs, datafusion/core/tests/sql/timestamp.rs, datafusion/physical-expr/src/datetime_expressions.rs
This PR extends `date_trunc` function, allowing `Date32` input as a second argument. Related tests are included.
=> feat: Support `Date32` to `TimestampNanosecond` coercion

datafusion/src/sql/planner.rs
=> fix: Window function don't work with only one Following bound

datafusion/common/src/scalar.rs, datafusion/physical-expr/src/coercion_rule/binary_rule.rs
This PR adds `Utf8 * Interval` coercion support. It also adds support for `Interval` types to be converted to a NULL `ScalarValue` instance of the respective type, and extends `ScalarValue::is_null` function to also return `true` for `Interval` types.
=> feat: Add Utf8 coercion for intervals

datafusion/physical-expr/src/coercion_rule/binary_rule.rs
This PR allows planning expressions where interval is being multiplied by a decimal number. There is currently no execution support.
=> feat: Allow `Decimal * Interval` expression planning

datafusion/core/src/physical_plan/functions.rs, datafusion/physical-expr/src/coercion_rule/binary_rule.rs
This PR allows planning (but not execution) of new expressions:
- `DatePart` with `Interval` as argument
- `Timestamp - Timestamp` binary expressions
- `Float * Interval` binary expressions
=> feat: Support planning extra expressions

datafusion/core/src/physical_plan/functions.rs
This PR adds support for planning (but not execution) of the listed scalar functions:
- `LOG(numeric, numeric)`
- `ROUND(numeric, int)`
=> feat: Support planning `LOG` and `ROUND` scalar functions with two arguments

datafusion/core/src/logical_plan/builder.rs, datafusion/core/src/logical_plan/mod.rs, datafusion/core/src/logical_plan/plan.rs, datafusion/core/src/optimizer/projection_drop_out.rs, datafusion/core/src/optimizer/projection_push_down.rs, datafusion/core/src/optimizer/utils.rs, datafusion/core/src/physical_plan/planner.rs, datafusion/core/src/physical_plan/subquery.rs, datafusion/core/src/sql/planner.rs, datafusion/core/tests/sql/subquery.rs
This PR is a first in series on improving subquery support (in an attempt to [split the large PR into smaller chunks](https://github.com/cube-js/arrow-datafusion/pull/110)) enabling scalar subqueries in `WHERE` and laying the groundwork for supporting other types of subqueries.
TODO:
=> feat: Support scalar subquery in `WHERE`

datafusion/physical-expr/src/expressions/case.rs
This PR adds support for matching `TimestampNanosecond` values in `CASE` expressions.
=> feat: Support `TimestampNanosecond` in `CASE`

Cargo.lock, datafusion-cli/Cargo.lock, datafusion/common/Cargo.toml, datafusion/common/src/scalar.rs, datafusion/core/Cargo.toml, datafusion/core/src/datasource/listing/helpers.rs, datafusion/core/src/logical_plan/expr_rewriter.rs, datafusion/core/src/logical_plan/expr_schema.rs, datafusion/core/src/logical_plan/expr_visitor.rs, datafusion/core/src/logical_plan/plan.rs, datafusion/core/src/optimizer/common_subexpr_eliminate.rs, datafusion/core/src/optimizer/simplify_expressions.rs, datafusion/core/src/optimizer/utils.rs, datafusion/core/src/physical_plan/planner.rs, datafusion/core/src/physical_plan/subquery.rs, datafusion/core/src/sql/planner.rs, datafusion/core/src/sql/utils.rs, datafusion/core/tests/sql/expr.rs, datafusion/core/tests/sql/subquery.rs, datafusion/expr/Cargo.toml, datafusion/expr/src/columnar_value.rs, datafusion/expr/src/expr.rs, datafusion/physical-expr/src/expressions/any.rs
=> feat: Subquery - ANY, ALL and IN support

Cargo.lock, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml
This PR bumps cube-js/arrow-rs@f32dc0f, altering the way `Float` types are converted to `Utf8`, trimming the ".0" postfix if a float has no fractional part. This is in accordance with how PostgreSQL converts floats to text, and does not affect `Decimal` (numeric) which retain their fractional part even if it is 0.
=> fix: Trim ".0" postfix when converting `Float` to `Utf8`

Cargo.lock, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml
This PR bumps cube-js/arrow-rs@70e71d1, adding support for parsing timestamp strings as dates. This is supported in Postgres, where the time and timezone would be ignored.
=> feat: Parse timestamp strings as `Date32`

Cargo.lock, datafusion-cli/Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/core/src/sql/planner.rs, datafusion/cube_ext/Cargo.toml, datafusion/expr/Cargo.toml, datafusion/expr/src/binary_rule.rs, datafusion/expr/src/operator.rs, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/expressions/binary.rs
This PR bumps cube-js/arrow-rs@d9c12d7 and adds `Exponentiate` binary operator which takes two numeric types and evaluates an exponentiation (pow fn). Related tests are included.
=> feat: Add `Exponentiate` operator

datafusion/Cargo.toml
```
tokio v0.1.22
└── tracing-futures v0.2.5
├── datafusion v4.0.0-SNAPSHOT (/Users/ovr/projects/cube/arrow-datafusion/datafusion)
│   ├── arrow-benchmarks v4.0.0-SNAPSHOT (/Users/ovr/projects/cube/arrow-datafusion/benchmarks)
│   └── datafusion-cli v4.0.0-SNAPSHOT (/Users/ovr/projects/cube/arrow-datafusion/datafusion-cli)
│   [dev-dependencies]
│   └── datafusion-examples v4.0.0-SNAPSHOT (/Users/ovr/projects/cube/arrow-datafusion/datafusion-examples)
└── tonic v0.4.3
└── arrow-flight v5.0.0 (https://github.com/cube-js/arrow-rs.git?branch=cube#ba5455c2)
[dev-dependencies]
└── datafusion-examples v4.0.0-SNAPSHOT (/Users/ovr/projects/cube/arrow-datafusion/datafusion-examples)
[dev-dependencies]
└── datafusion-examples v4.0.0-SNAPSHOT …
```
=> chore: Remove tokio 0.1 support for tracing

datafusion/common/src/scalar.rs, datafusion/core/src/physical_plan/hash_join.rs, datafusion/core/src/physical_plan/hash_utils.rs, datafusion/cube_ext/src/temporal.rs, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/expressions/binary_distinct.rs
Closes #.
This makes some queries, such as `SELECT (CAST('2021-01-02 12:34:56.123456789' AS TIMESTAMP) - CAST('2021-02-02 12:00:00.000' AS TIMESTAMP)) AS result;`, run.
Timestamp subtraction, producing intervals, is implemented.
=> feat: Timestamp subtraction

.github/workflows/rust.yml, datafusion/physical-expr/src/expressions/binary_distinct.rs
This PR supports expressions like `timestamp datatype value - date datatype value`.
=> Feat: timestamp subtract date

datafusion/core/src/sql/planner.rs, datafusion/core/tests/sql/expr.rs, datafusion/expr/src/binary_rule.rs, datafusion/physical-expr/src/expressions/binary_distinct.rs
This PR adds support for `Interval(MonthDayNano) * Int64` expression evaluation with tests included.
It also adds coercion for `Interval + Interval` or `Interval - Interval` expressions.
=> feat: Support `MonthDayNano` interval int multiply

datafusion/expr/src/aggregate_function.rs, datafusion/physical-expr/src/expressions/average.rs, datafusion/physical-expr/src/expressions/sum.rs
This PR adds support for planning and execution of aggregate functions `SUM` and `AVG` with input type of `Null`. The output type is `Null` as well. Related tests are included.
=> feat: Support `Null` input type in `Sum` and `Avg` functions

Cargo.lock, datafusion-cli/Cargo.toml, datafusion-examples/Cargo.toml, datafusion/common/Cargo.toml, datafusion/common/src/scalar.rs, datafusion/core/Cargo.toml, datafusion/core/fuzz-utils/Cargo.toml, datafusion/core/src/sql/planner.rs, datafusion/cube_ext/Cargo.toml, datafusion/cube_ext/src/temporal.rs, datafusion/expr/Cargo.toml, datafusion/jit/Cargo.toml, datafusion/physical-expr/Cargo.toml, datafusion/physical-expr/src/datetime_expressions.rs, datafusion/physical-expr/src/expressions/binary_distinct.rs
I've skimmed through code looking for anything that looked like bit packing for intervals, replaced it with `to_parts` and `make_value` from arrow,  fixed some of overflow/underflow handling and used named type aliases in place of underlying integers
TODO: reference proper commit in `Bump arrow` after https://github.com/cube-js/arrow-rs/pull/37 is merged
=> refactor: Use arrow interval packing

.github/workflows/rust.yml, datafusion/src/cube_ext/util.rs
Use `$crate` to import `arrow` from `datafusion` crate, not from callee context
=> Improve cube_ext macro hygiene

datafusion/src/physical_plan/parquet.rs
Related: https://github.com/cube-js/cube/pull/8756
=> refactor: Removed MetadataCacheFactory::build_writer_props

datafusion/src/physical_plan/planner.rs, datafusion/src/physical_plan/sort.rs
This is a bugfix in input_sorted_by_group_key.  Currently, when considering whether to replace hash aggregation with inplace aggregation, it is the case that if there are single value columns in the sort key that aren't part of the prefix of the sort key that the group key matches, we will fail to use Inplace aggregation.
This also implements a basic output_hints() implementation for SortExec, but (while generally useful) that is for the sake of the test that was written.
=> fix: Make input_sorted_by_group_key tolerate unrelated single value columns outside the group key prefix
