cube-js/arrow-datafusion

datafusion/src/sql/planner.rs

Original change in CubeStore fork was motivated by the lack of support
in filter mirroring. No longer a problem in the current version.

Restore to the upstream version of IN expression planning

---

datafusion/src/physical_plan/datetime_expressions.rs

feat: Support quarter granularity in date_trunct fn (#1667)

---

ballista/rust/client/Cargo.toml
ballista/rust/core/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/src/sql/planner.rs
datafusion/expr/Cargo.toml

This PR adds support for SQLExpr::DotExpr to access fields in a struct returned by a function.

feat: Support field access with dot expression

---

ballista/rust/client/Cargo.toml
ballista/rust/core/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/tests/sql/expr.rs
datafusion/expr/Cargo.toml

feat: Initial support for IS TRUE|FALSE

---

datafusion/core/src/sql/planner.rs

More types in cast

---

ballista/rust/core/Cargo.toml
ballista/rust/executor/Cargo.toml
datafusion-cli/Cargo.toml
datafusion-examples/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/fuzz-utils/Cargo.toml
datafusion/core/src/sql/planner.rs
datafusion/core/tests/sql/expr.rs
datafusion/cube_ext/Cargo.toml
datafusion/expr/Cargo.toml
datafusion/expr/src/expr.rs
datafusion/expr/src/operator.rs
datafusion/jit/Cargo.toml
datafusion/physical-expr/Cargo.toml
datafusion/physical-expr/src/coercion_rule/binary_rule.rs
datafusion/physical-expr/src/expressions/binary.rs

This PR adds support for `ILIKE` and `NOT ILIKE` operators, as well as related test.

Support ILIKE operators

---

ballista/rust/client/Cargo.toml
ballista/rust/core/Cargo.toml
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/src/sql/planner.rs
datafusion/expr/Cargo.toml

This PR adds support for parsing expressions in `LIMIT` by bumping `sqlparser-rs`.
No such expressions are being added to `arrow-datafusion` in this PR, but this helps with value placeholders.

feat: Allow expressions in `LIMIT`

---

ballista/rust/client/src/context.rs
ballista/rust/scheduler/src/planner.rs
ballista/rust/scheduler/src/scheduler_server/grpc.rs
benchmarks/src/bin/tpch.rs
datafusion/core/Cargo.toml
datafusion/core/benches/sql_planner.rs
datafusion/core/src/dataframe.rs
datafusion/core/src/execution/context.rs
datafusion/core/tests/custom_sources.rs
datafusion/core/tests/parquet_pruning.rs
datafusion/core/tests/path_partition.rs
datafusion/core/tests/sql/projection.rs
datafusion/core/tests/sql/udf.rs
datafusion/core/tests/statistics.rs

Stop optimizing queries twice (#2369)

---

datafusion/physical-expr/src/coercion_rule/binary_rule.rs

This PR adds support for type coercion between an interval and a number (Int64) in a binary expression with a multiplication operator.

feat: Support interval multiplication coercion (no cast)

---

datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml

This PR bumps `sqlparser-rs` in order to fix `INTERVAL + INTERVAL` expressions.

chore: Bump cube-js/sqlparser-rs@4b67b56

---

datafusion/core/src/sql/planner.rs

This PR fixes an issue when `TableFactor::Derived` tried to parse subquery column alias as if it could have a relation while the relation field should always have been empty. This fixes queries like `SELECT "a.b" FROM (SELECT 1 "a.b") c`. Any query that had a FROM subquery and aliases with a single dot would fail. Aliases with more than one dot would be unaffected due to the code logic. It also adds a related test.

fix: Don't try to extract relation from subquery column alias

---

datafusion/src/physical_plan/planner.rs

fix: Fix planing for tables with unique keys

---

datafusion/Cargo.toml

chore(datafusion): Upgrade sqlparser (placeholder support)

---

.github/workflows/rust.yml
datafusion/src/optimizer/projection_push_down.rs

fix: Projection push down breaks aggregations

---

datafusion/src/optimizer/projection_push_down.rs

fix: Fix error in projection pushdown

---

Cargo.lock
datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml

This PR bumps cube-js/sqlparser-rs@037562f, adding support for `SET ROLE` statement.

chore: Bump cube-js/sqlparser-rs@037562f

---

datafusion/core/src/logical_plan/mod.rs
datafusion/core/src/physical_plan/functions.rs
datafusion/core/tests/sql/functions.rs
datafusion/expr/src/built_in_function.rs
datafusion/expr/src/expr_fn.rs
datafusion/physical-expr/src/math_expressions.rs
datafusion/proto/proto/datafusion.proto
datafusion/proto/src/from_proto.rs
datafusion/proto/src/to_proto.rs

This PR adds `PI` function from upstream. Related tests are included.

feat: implementation of the constant "Pi" (#5965)

---

datafusion/src/physical_plan/hash_join.rs

fix: panic in hash join

---

Cargo.lock
datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml

This PR bumps cube-js/sqlparser-rs@dca8d90, fixing unary minus precedence.

fix: Fix unary minus operator precedence

---

datafusion/core/tests/sql/expr.rs
datafusion/cube_ext/src/temporal.rs
datafusion/physical-expr/src/datetime_expressions.rs

feat: EXTRACT(EPOCH, ...) support

---

.github/workflows/rust.yml
datafusion/src/cube_ext/rolling.rs

fix: Error in queries with GROUP BY DIMENSION

---

Cargo.lock
datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/core/src/sql/planner.rs
datafusion/core/tests/sql/expr.rs
datafusion/expr/Cargo.toml

feat: Strings with Unicode Escapes

---

Cargo.lock
datafusion-cli/Cargo.lock
datafusion/common/Cargo.toml
datafusion/core/Cargo.toml
datafusion/expr/Cargo.toml

This PR bumps cube-js/sqlparser-rs@347f769, adding support for placeholders in `OFFSET` and `FETCH ...`.

feat: Support placeholders in `OFFSET`, `FETCH ...`

---

datafusion/core/src/logical_plan/builder.rs
datafusion/core/src/logical_plan/mod.rs
datafusion/core/src/logical_plan/plan.rs
datafusion/core/src/optimizer/projection_drop_out.rs
datafusion/core/src/optimizer/projection_push_down.rs
datafusion/core/src/optimizer/utils.rs
datafusion/core/src/physical_plan/planner.rs
datafusion/core/src/physical_plan/subquery.rs
datafusion/core/src/sql/planner.rs
datafusion/core/tests/sql/subquery.rs

This PR builds on top of #111, adding support for `EXISTS` subqueries. Related tests are included.

feat: Support `EXISTS` subquery

---

datafusion/core/src/sql/planner.rs

This PR adds support for `FETCH <FIRST | NEXT> n ROWS ONLY` clause that works like a `LIMIT`. Related test is included.

feat: Support `FETCH ... n ROWS ONLY`

---

datafusion/src/optimizer/simplify_expressions.rs

fix: Error in optimization for nested boolean expressions

---

datafusion-cli/Cargo.lock
datafusion/common/src/lib.rs
datafusion/common/src/scalar.rs
datafusion/expr/src/binary_rule.rs
datafusion/physical-expr/Cargo.toml
datafusion/physical-expr/src/expressions/binary.rs
datafusion/physical-expr/src/expressions/binary_distinct.rs
datafusion/physical-expr/src/expressions/mod.rs
datafusion/physical-expr/src/expressions/negative.rs

This PR adds support for distinct binary expression types, allowing binary operations like `Timestamp + Interval` to be planned and evaluated.

feat: Support distinct binary expression types

---

datafusion/core/src/physical_plan/planner.rs
datafusion/core/src/sql/planner.rs

This PR allows planning (but not execution) of window functions with window frames. Related test is included.

feat: Allow planning window functions with window frames

---

datafusion/src/optimizer/projection_push_down.rs

fix: Fix wrong optimization on total count queries

---

datafusion/core/src/logical_plan/builder.rs

fix(cubesql): Rollup doesn't work over aliased columns

---

datafusion/core/src/physical_plan/hash_join.rs

Remove this after rebasing on top of commit ac2e5d15 "Support type coercion for equijoin (#4666)". It was first released at DF 16.0

Crude hack to introduce type coercion for hash join keys

---

benchmarks/src/bin/tpch.rs
datafusion-cli/src/main.rs
datafusion-examples/examples/flight_server.rs
datafusion/src/datasource/parquet.rs
datafusion/src/execution/context.rs
datafusion/src/logical_plan/builder.rs
datafusion/src/physical_optimizer/pruning.rs
datafusion/src/physical_plan/mod.rs
datafusion/src/physical_plan/parquet.rs

MetadataCacheFactory changes
